import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

type Section = { heading: string; paragraphs?: string[]; bullets?: string[] };
type Page = { title: string; lead: string; sections: Section[] };
const updated = "29 August 2026";
const business = {
  legalName: "Elysium Enterprise",
  registration: "Registered with the Corporate Affairs Commission; registration number available to competent authorities and verified counterparties upon lawful request.",
  address: "Mainland, Lagos, Nigeria",
  supportEmail: "support@socialbooster.net.ng",
  privacyEmail: "vincenttheoikechukwu@gmail.com",
};

const pages: Record<string, Page> = {
  "how-it-works": { title: "How Social Booster Works", lead: "Start in minutes: create your account, pay securely, choose the right social media service and track every order.", sections: [{ heading: "1. Create and verify your account", paragraphs: ["Register with your first name, last name and email address. Open the activation email and verify your address before signing in. If the message is not in your Inbox, check Spam, Junk or Promotions."] }, { heading: "2. Fund your wallet", paragraphs: ["Choose an amount in naira and complete payment on the secure Flutterwave checkout. Successful payments are verified before wallet credit is posted."] }, { heading: "3. Select a service", paragraphs: ["Choose a category, compare services and read the description, limits, refill availability and calculated charge. Confirm the target URL carefully before submitting."] }, { heading: "4. Track the order", paragraphs: ["Follow progress from your order history. Eligible refill or cancellation controls appear on the individual order page."] }] },
  africa: { title: "Social Media Services Across Africa", lead: "A simpler way for African creators, businesses, agencies and resellers to discover services and manage orders online.", sections: [{ heading: "Who can use Social Booster", paragraphs: ["Customers in African countries can create an account, verify their email, browse available services and use the customer dashboard on desktop or mobile."] }, { heading: "Payments across African markets", paragraphs: ["Checkout methods vary by country, bank and your Flutterwave merchant configuration. International cards may process in naira through the customer's bank, while local cards, bank transfer and mobile money require the relevant Flutterwave country and currency options to be enabled."] }, { heading: "What is available today", bullets: ["Responsive account and order management from any supported location", "English-language service descriptions and support guidance", "Secure Flutterwave checkout", "Prices and wallet accounting in Nigerian naira", "Clear payment and order status messages"] }, { heading: "Expansion requirements", paragraphs: ["For a fully localized experience in every African market, Social Booster will need additional settlement currencies, country-specific Flutterwave payment methods, French-language pages for Francophone markets and verified support coverage for each region."] }] },
  about: { title: "About Social Booster", lead: "A Nigerian service marketplace built around clear pricing, secure payments and accountable order tracking.", sections: [{ heading: "What we provide", paragraphs: ["Social Booster gives customers one place to compare available services, fund a naira wallet, submit permitted orders and follow their progress."] }, { heading: "Our operating principles", bullets: ["Clear charges before submission", "Server-verified wallet payments", "Traceable wallet and order records", "Responsible use requirements", "Support for genuine account and order issues"] }] },
  contact: { title: "Contact support", lead: "Get help with your account, wallet payment or order.", sections: [{ heading: "Before contacting us", bullets: ["For payment issues, include the Flutterwave transaction ID and amount.", "For order issues, include your Social Booster order ID.", "Never send your password, card PIN, CVV or one-time password."] }, { heading: "Support hours and response", paragraphs: ["Send one clear message with the relevant reference number. Support aims to respond within 24 hours through your dashboard ticket, our official support email or the official WhatsApp number shown on this page."] }] },
  faq: { title: "Frequently asked questions", lead: "Clear answers about accounts, payments, orders and wallet activity.", sections: [{ heading: "Why must I verify my email?", paragraphs: ["Email verification protects your account and confirms where important account messages should be delivered."] }, { heading: "When is my wallet credited?", paragraphs: ["A successful payment is credited after the server independently verifies the transaction reference, status, amount and currency."] }, { heading: "Can an order be changed?", paragraphs: ["Many orders cannot be changed after submission. Review the service, URL and quantity carefully before confirming."] }, { heading: "How do refunds work?", paragraphs: ["Eligible order refunds are returned to the customer wallet. See the Refund Policy for details."] }] },
  terms: { title: "Terms of Service", lead: "The rules that apply when you create an account, fund a wallet or submit an order.", sections: [{ heading: "Agreement and eligibility", paragraphs: ["By using Social Booster, you agree to these Terms, the Privacy Policy, Refund Policy and Acceptable Use Policy. You must provide accurate account information and have legal capacity to enter into this agreement."] }, { heading: "Accounts and security", bullets: ["Use your real first and last name and maintain access to your verified email address.", "Keep your password and devices secure and do not share accounts.", "Notify support promptly if you suspect unauthorized access.", "We may require renewed authentication, additional evidence or account review before a sensitive action.", "We may restrict accounts involved in fraud, abuse or policy violations."] }, { heading: "Wallet payments", paragraphs: ["Wallet credits are posted only after server-side payment verification. Wallet balances are service credits for purchasing eligible services and are not bank accounts. Payment fees charged by the payment processor may be separate from the amount credited."] }, { heading: "Orders", paragraphs: ["You are responsible for choosing the correct service, target URL and quantity. Availability, delivery speed, refill eligibility and cancellation availability vary by service. Submission does not guarantee a particular commercial or social-media outcome."] }, { heading: "Cancellation and delivery issues", paragraphs: ["A cancellation button means that a request can be sent for review; it does not guarantee cancellation. The order remains active until its live status confirms cancellation. A delivery report opens a support case so the order status, start count, remaining quantity and provider evidence can be reviewed. Do not submit duplicate requests while a case is open."] }, { heading: "Prohibited use", paragraphs: ["You must not use the service for fraud, harassment, impersonation, unlawful activity, political manipulation, misleading conduct, fabricated reviews or violations of third-party rights."] }, { heading: "Availability and liability", paragraphs: ["Services may be delayed, changed, suspended or discontinued. To the extent permitted by applicable law, liability is limited to the amount paid for the affected service. Nothing in these Terms excludes rights that cannot legally be excluded."] }, { heading: "Governing law and changes", paragraphs: ["These Terms are governed by applicable laws of the Federal Republic of Nigeria. Material changes will be published with a revised effective date."] }] },
  privacy: { title: "Privacy Policy", lead: "How personal information is collected, used, protected and shared.", sections: [{ heading: "Information we collect", bullets: ["Name, email address and authentication identifiers", "Wallet, payment-reference and transaction records", "Order details, target URLs and service history", "Support communications", "Security and technical information such as timestamps and IP-related fraud signals", "On public pages, consented analytics and advertising information such as page views, device or browser details and advertising identifiers"] }, { heading: "Why we use it", bullets: ["Create and secure your account", "Verify payments and maintain wallet records", "Submit and track requested services", "Prevent fraud, investigate incidents and enforce policies", "Respond to support requests and meet legal obligations", "With your choice, measure public-site performance and support advertising"] }, { heading: "Lawful grounds", paragraphs: ["Depending on the activity, processing is necessary to perform our contract with you, comply with legal obligations, protect legitimate security and operational interests, or act on your consent. Optional analytics and advertising technologies are controlled through the privacy choices interface."] }, { heading: "Service providers and transfers", paragraphs: ["We share only necessary information with providers that support authentication, hosting, database operations, payments, email delivery, analytics, advertising and order fulfilment. These providers process information under their own terms and applicable safeguards."] }, { heading: "Retention and security", paragraphs: ["Records are retained only as long as reasonably necessary for service delivery, financial reconciliation, fraud prevention, dispute handling and legal compliance. We use access controls, secure sessions, server-side authorization, session revocation checks and audit records, but no online service can guarantee absolute security."] }, { heading: "Your privacy rights", paragraphs: ["Subject to applicable law, you may request access, correction, deletion, restriction, objection or portability of eligible personal data, withdraw consent for optional technologies, and lodge a complaint with the Nigeria Data Protection Commission. Identity verification may be required before fulfilling a request."] }, { heading: "Children", paragraphs: ["Social Booster is not intended for children who cannot lawfully consent to these services. Do not create an account for a child without lawful authority."] }] },
  "refund-policy": { title: "Refund Policy", lead: "When wallet credits, order refunds and payment reversals may apply.", sections: [{ heading: "Wallet deposits", paragraphs: ["A verified wallet deposit is normally final once credited. If a payment is successful but missing, provide the Flutterwave transaction ID so it can be verified and reconciled. Duplicate credits are prevented automatically."] }, { heading: "Order refunds", paragraphs: ["If an order is rejected before fulfilment, the eligible charge is returned to the wallet. A full wallet refund may apply after a live order status confirms failure or cancellation. A partial order may receive a proportional wallet refund based on the confirmed undelivered quantity."] }, { heading: "Cancellation requests", paragraphs: ["Requesting cancellation does not itself stop an active order or create an immediate refund. Social Booster first submits or reviews the request, then verifies the live order status. Any eligible refund is calculated only after cancellation or partial delivery is confirmed and is protected against duplicate crediting."] }, { heading: "Delivery disputes", paragraphs: ["A report should identify the order and problem. We compare the recorded target, quantity, start count, remaining quantity, service terms and live fulfilment evidence before deciding whether completion, refill, cancellation, partial credit or further investigation applies."] }, { heading: "Non-refundable situations", bullets: ["Incorrect target URL or quantity supplied by the customer", "A completed service that matches the selected service description", "Losses caused by changes made to the target account during delivery", "Requests outside an advertised refill or cancellation period", "Payment-processor fees, except where applicable law requires otherwise"] }, { heading: "Review process", paragraphs: ["Refund eligibility is determined from payment records, order status and provider evidence. Approved order refunds are posted to the wallet ledger. Statutory rights remain unaffected."] }] },
  "acceptable-use": { title: "Acceptable Use Policy", lead: "Standards that protect customers, platforms and the public.", sections: [{ heading: "You must not", bullets: ["Use services for fraud, deception, harassment or intimidation", "Impersonate another person or target an account without authority", "Promote illegal content, hate, violence or exploitation", "Manipulate political or civic processes", "Attempt to bypass service limits, security or payment controls", "Submit malware, stolen credentials or private information", "Resell or use services in a way that violates applicable law or platform rules"] }, { heading: "Enforcement", paragraphs: ["We may reject orders, restrict features, suspend accounts, preserve relevant records or cooperate with lawful investigations where misuse is suspected. Enforcement decisions consider severity, repetition and risk."] }] },
  "cookie-policy": { title: "Cookie Policy", lead: "How browser storage supports secure access, preferences, analytics and advertising.", sections: [{ heading: "Essential storage", paragraphs: ["Social Booster uses essential session cookies and related browser storage to keep signed-in users authenticated, protect private account pages and remember required security state. These technologies are necessary for the service to function and cannot be disabled through the preference panel."] }, { heading: "Analytics", paragraphs: ["With your permission on public pages, Google Analytics helps us understand page visits and website performance. Analytics is not loaded on customer or administration routes, and the current configuration requests IP anonymisation."] }, { heading: "Advertising", paragraphs: ["With your permission on public pages, Google AdSense may use cookies or similar identifiers to deliver, measure and protect advertising. Google may process information under its own policies. Advertising is not loaded on customer or administration routes."] }, { heading: "Your choices", paragraphs: ["The Privacy choices control lets you accept all optional technologies, allow analytics only, or use essential storage only. You can reopen that control at any time to change your selection. Blocking essential cookies in your browser will prevent account login and dashboard access."] }] },
};

const legalAdditions: Record<string, Section[]> = {
  terms: [{ heading: "Pricing, taxes and currency", paragraphs: ["Prices are displayed in Nigerian naira unless expressly stated otherwise. The final charge shown before confirmation applies to that order. Customers are responsible for taxes, bank charges or currency-conversion costs imposed by their own institution."] }, { heading: "Complaints and dispute resolution", paragraphs: ["Contact support first with the relevant account email, payment reference or order ID. We will review platform records and respond through an official support channel. If a dispute cannot be resolved informally, the parties retain any remedies available under applicable Nigerian law."] }, { heading: "Contact and notices", paragraphs: ["Questions about these Terms should be submitted through the Contact page. Legal notices must identify the sender and provide enough information for the matter to be verified."] }],
  privacy: [{ heading: "Payment information", paragraphs: ["Card and bank credentials are entered on the payment processor's secure checkout and are not stored by Social Booster. We retain transaction references, amounts, status and reconciliation records required to operate the wallet and investigate disputes."] }, { heading: "International processing", paragraphs: ["Hosting, authentication, payment and service infrastructure may process limited information outside Nigeria. Where applicable, we rely on contractual, technical and organisational safeguards appropriate to the transfer."] }, { heading: "Privacy requests and complaints", paragraphs: ["Submit privacy requests through the Contact page and clearly state the right you wish to exercise. We may request reasonable identity verification. You may also contact the Nigeria Data Protection Commission if you believe a privacy concern has not been properly resolved."] }],
  "refund-policy": [{ heading: "How to request a review", bullets: ["Open a support ticket from the signed-in dashboard.", "Include the order ID or payment reference and a concise description of the issue.", "Do not submit passwords, PINs, CVVs or one-time codes.", "Allow the order and payment records to be checked before opening a duplicate request."] }, { heading: "Processing method and timing", paragraphs: ["Eligible refund requests are reviewed within 24 hours. Approved order refunds are normally returned to the Social Booster wallet within 24 hours and recorded in transaction history. A payment reversal to the original method, where legally required or expressly approved, depends on the payment processor and receiving bank and may take longer."] }, { heading: "Chargebacks and duplicate recovery", paragraphs: ["Contact support before initiating a chargeback so the transaction can be investigated. Fraudulent chargebacks, duplicate recovery or spending a credit that is later reversed may result in account restriction and recovery of the resulting negative balance."] }],
  "acceptable-use": [{ heading: "Responsible ordering", bullets: ["Use only target URLs you are authorised to promote.", "Read the selected service description and platform rules before ordering.", "Do not represent platform activity as verified customer opinion, genuine endorsement or guaranteed commercial performance.", "Do not combine the service with spam, credential theft, deceptive redirects or unauthorised automation."] }, { heading: "Reporting suspected misuse", paragraphs: ["Report suspected abuse through the Contact page with the relevant public URL or order information. Do not include passwords or unnecessary personal data. We may preserve records and restrict activity while a credible report is reviewed."] }, { heading: "Review and appeal", paragraphs: ["A customer may ask support to review an enforcement decision and provide relevant context. Reinstatement is not guaranteed where continued access would create legal, security, payment or platform risk."] }],
  "cookie-policy": [{ heading: "Storage currently used", bullets: ["Secure session cookies that keep authenticated areas private", "Browser storage required by Firebase authentication and security controls", "Versioned preference storage that records your optional analytics and advertising choice"] }, { heading: "Third parties", paragraphs: ["Google provides the optional analytics and advertising technologies. Its services may receive page, device, browser and advertising information only after the applicable choice. Review Google's privacy information and browser controls for additional options."] }, { heading: "Updates to this policy", paragraphs: ["We will revise the effective date when cookie practices materially change. Review this page periodically, particularly after new analytics, advertising or personalisation features are announced."] }],
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params, item = pages[slug]; return item ? { title: item.title, description: item.lead, alternates: { canonical: `/${slug}` } } : { title: "Page not found", robots: { index: false } }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params, item = pages[slug]; if (!item) notFound();
  const legal = ["terms", "privacy", "refund-policy", "acceptable-use", "cookie-policy"].includes(slug);
  const sections = legal ? [...item.sections, ...(legalAdditions[slug] || [])] : item.sections;
  const whatsapp = (process.env.NEXT_PUBLIC_WHATSAPP || "").replace(/\D/g, "");
  return <><SiteHeader /><main className="shell" style={{ minHeight: "65vh", padding: "90px 0" }}><span className="eyebrow">Social Booster</span><h1 style={{ fontSize: "clamp(2.8rem,7vw,5.2rem)", letterSpacing: "-.06em", maxWidth: 900, margin: "18px 0" }}>{item.title}</h1><p className="muted" style={{ fontSize: 20, lineHeight: 1.7, maxWidth: 760 }}>{item.lead}</p>{legal ? <div className="notice" style={{ marginTop: 24, maxWidth: 760 }}><strong>Effective date: {updated}</strong><p className="muted" style={{ margin: "8px 0 0" }}>Social Booster is operated by {business.legalName} from {business.address}. Questions and formal requests can be submitted through our <Link href="/contact">Contact page</Link>.</p></div> : null}{legal || slug === "contact" ? <section className="glass card" style={{ marginTop: 24, maxWidth: 760 }}><span className="eyebrow">Business contact</span><h2>{business.legalName}</h2><p className="muted">{business.registration}<br />Business address: {business.address}<br />Support: <a href={`mailto:${business.supportEmail}`}>{business.supportEmail}</a><br />Privacy requests: <a href={`mailto:${business.privacyEmail}`}>{business.privacyEmail}</a><br />Support response target: within 24 hours.</p></section> : null}{slug === "contact" && whatsapp ? <p style={{ marginTop: 28 }}><a className="btn primary" href={`https://wa.me/${whatsapp}`} target="_blank" rel="noreferrer">Message support on WhatsApp</a></p> : null}<div className="legal-wrap" style={{ marginTop: 44 }}><article className="glass legal-copy">{sections.map((section, index) => { const id = `section-${index + 1}`; return <section key={section.heading} id={id}><h2>{section.heading}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}</section>; })}{legal ? <section><h2>Policy contact</h2><p>Policy questions, payment disputes and abuse reports may be sent to <a href={`mailto:${business.supportEmail}`}>{business.supportEmail}</a>. Privacy requests may be sent to <a href={`mailto:${business.privacyEmail}`}>{business.privacyEmail}</a>. Include only the information needed to locate the relevant record.</p></section> : null}</article><aside className="glass legal-nav"><strong>On this page</strong>{sections.map((section, index) => <a key={section.heading} href={`#section-${index + 1}`}>{section.heading}</a>)}<strong style={{ marginTop: 18 }}>{legal ? "Related policies" : "Explore"}</strong>{(legal ? [["Terms", "/terms"], ["Privacy", "/privacy"], ["Refunds", "/refund-policy"], ["Acceptable use", "/acceptable-use"], ["Cookies", "/cookie-policy"]] : [["How it works", "/how-it-works"], ["FAQ", "/faq"], ["Contact", "/contact"], ["Create account", "/register"]]).map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</aside></div></main><SiteFooter /></>;
}
