import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";

type Section = { heading: string; paragraphs?: string[]; bullets?: string[] };
type Page = { title: string; lead: string; sections: Section[] };
const updated = "23 August 2026";

const pages: Record<string, Page> = {
  "how-it-works": { title: "How Social Booster Works", lead: "Start in minutes: create your account, pay securely, choose the right social media service and track every order.", sections: [{ heading: "1. Create and verify your account", paragraphs: ["Register with your first name, last name and email address. Open the activation email and verify your address before signing in. If the message is not in your Inbox, check Spam, Junk or Promotions."] }, { heading: "2. Fund your wallet", paragraphs: ["Choose an amount in naira and complete payment on the secure Flutterwave checkout. Successful payments are verified before wallet credit is posted."] }, { heading: "3. Select a service", paragraphs: ["Choose a category, compare services and read the description, limits, refill availability and calculated charge. Confirm the target URL carefully before submitting."] }, { heading: "4. Track the order", paragraphs: ["Follow progress from your order history. Eligible refill or cancellation controls appear on the individual order page."] }] },
  africa: { title: "Social Media Services Across Africa", lead: "A simpler way for African creators, businesses, agencies and resellers to discover services and manage orders online.", sections: [{ heading: "Who can use Social Booster", paragraphs: ["Customers in African countries can create an account, verify their email, browse available services and use the customer dashboard on desktop or mobile."] }, { heading: "Payments across African markets", paragraphs: ["Checkout methods vary by country, bank and your Flutterwave merchant configuration. International cards may process in naira through the customer's bank, while local cards, bank transfer and mobile money require the relevant Flutterwave country and currency options to be enabled."] }, { heading: "What is available today", bullets: ["Responsive account and order management from any supported location", "English-language service descriptions and support guidance", "Secure Flutterwave checkout", "Prices and wallet accounting in Nigerian naira", "Clear payment and order status messages"] }, { heading: "Expansion requirements", paragraphs: ["For a fully localized experience in every African market, Social Booster will need additional settlement currencies, country-specific Flutterwave payment methods, French-language pages for Francophone markets and verified support coverage for each region."] }] },
  about: { title: "About Social Booster", lead: "A Nigerian service marketplace built around clear pricing, secure payments and accountable order tracking.", sections: [{ heading: "What we provide", paragraphs: ["Social Booster gives customers one place to compare available services, fund a naira wallet, submit permitted orders and follow their progress."] }, { heading: "Our operating principles", bullets: ["Clear charges before submission", "Server-verified wallet payments", "Traceable wallet and order records", "Responsible use requirements", "Support for genuine account and order issues"] }] },
  contact: { title: "Contact support", lead: "Get help with your account, wallet payment or order.", sections: [{ heading: "Before contacting us", bullets: ["For payment issues, include the Flutterwave transaction ID and amount.", "For order issues, include your Social Booster order ID.", "Never send your password, card PIN, CVV or one-time password."] }, { heading: "Support channel", paragraphs: ["The public support email, telephone number and business address must be confirmed by the business owner before publication. Until then, use the administrative support workflow for account-specific requests."] }] },
  faq: { title: "Frequently asked questions", lead: "Clear answers about accounts, payments, orders and wallet activity.", sections: [{ heading: "Why must I verify my email?", paragraphs: ["Email verification protects your account and confirms where important account messages should be delivered."] }, { heading: "When is my wallet credited?", paragraphs: ["A successful payment is credited after the server independently verifies the transaction reference, status, amount and currency."] }, { heading: "Can an order be changed?", paragraphs: ["Many orders cannot be changed after submission. Review the service, URL and quantity carefully before confirming."] }, { heading: "How do refunds work?", paragraphs: ["Eligible order refunds are returned to the customer wallet. See the Refund Policy for details."] }] },
  terms: { title: "Terms of Service", lead: "The rules that apply when you create an account, fund a wallet or submit an order.", sections: [{ heading: "Agreement and eligibility", paragraphs: ["By using Social Booster, you agree to these Terms, the Privacy Policy, Refund Policy and Acceptable Use Policy. You must provide accurate account information and have legal capacity to enter into this agreement."] }, { heading: "Accounts and security", bullets: ["Keep your password and devices secure.", "Do not share accounts or impersonate another person.", "Notify support promptly if you suspect unauthorized access.", "We may restrict accounts involved in fraud, abuse or policy violations."] }, { heading: "Wallet payments", paragraphs: ["Wallet credits are posted only after payment verification. Wallet balances are service credits for purchasing eligible services and are not bank accounts. Payment fees charged by the payment processor may be separate from the amount credited."] }, { heading: "Orders", paragraphs: ["You are responsible for choosing the correct service, target URL and quantity. Availability, delivery speed, refill eligibility and cancellation availability vary by service. Submission does not guarantee a particular commercial or social-media outcome."] }, { heading: "Prohibited use", paragraphs: ["You must not use the service for fraud, harassment, impersonation, unlawful activity, political manipulation, misleading conduct or violations of third-party rights."] }, { heading: "Availability and liability", paragraphs: ["Services may be delayed, changed, suspended or discontinued. To the extent permitted by applicable law, liability is limited to the amount paid for the affected service. Nothing in these Terms excludes rights that cannot legally be excluded."] }, { heading: "Governing law and changes", paragraphs: ["These Terms are governed by applicable laws of the Federal Republic of Nigeria. Material changes will be published with a revised effective date."] }] },
  privacy: { title: "Privacy Policy", lead: "How personal information is collected, used, protected and shared.", sections: [{ heading: "Information we collect", bullets: ["Name, email address and authentication identifiers", "Wallet, payment-reference and transaction records", "Order details, target URLs and service history", "Support communications", "Security and technical information such as timestamps and IP-related fraud signals"] }, { heading: "Why we use it", bullets: ["Create and secure your account", "Verify payments and maintain wallet records", "Submit and track requested services", "Prevent fraud, investigate incidents and enforce policies", "Respond to support requests and meet legal obligations"] }, { heading: "Lawful grounds", paragraphs: ["Depending on the activity, processing is necessary to perform our contract with you, comply with legal obligations, protect legitimate security and operational interests, or act on your consent."] }, { heading: "Service providers and transfers", paragraphs: ["We share only necessary information with providers that support authentication, hosting, database operations, payments and order fulfilment. These providers process information under their own terms and applicable safeguards."] }, { heading: "Retention and security", paragraphs: ["Records are retained only as long as reasonably necessary for service delivery, financial reconciliation, fraud prevention, dispute handling and legal compliance. We use access controls, secure sessions, server-side authorization and audit records, but no online service can guarantee absolute security."] }, { heading: "Your privacy rights", paragraphs: ["Subject to applicable law, you may request access, correction, deletion, restriction, objection or portability of eligible personal data, and may lodge a complaint with the Nigeria Data Protection Commission. Identity verification may be required before fulfilling a request."] }, { heading: "Children", paragraphs: ["Social Booster is not intended for children who cannot lawfully consent to these services. Do not create an account for a child without lawful authority."] }] },
  "refund-policy": { title: "Refund Policy", lead: "When wallet credits, order refunds and payment reversals may apply.", sections: [{ heading: "Wallet deposits", paragraphs: ["A verified wallet deposit is normally final once credited. If a payment is successful but missing, provide the Flutterwave transaction ID so it can be verified and reconciled. Duplicate credits are prevented automatically."] }, { heading: "Order refunds", paragraphs: ["If an order is rejected before fulfilment, the eligible charge is returned to the wallet. Failed or cancelled orders may receive a full wallet refund. Partial orders may receive a proportional wallet refund based on the undelivered quantity."] }, { heading: "Non-refundable situations", bullets: ["Incorrect target URL or quantity supplied by the customer", "A completed service that matches the selected service description", "Losses caused by changes made to the target account during delivery", "Requests outside an advertised refill or cancellation period", "Payment-processor fees, except where applicable law requires otherwise"] }, { heading: "Review process", paragraphs: ["Refund eligibility is determined from payment records, order status and provider evidence. Approved order refunds are posted to the wallet ledger. Statutory rights remain unaffected."] }] },
  "acceptable-use": { title: "Acceptable Use Policy", lead: "Standards that protect customers, platforms and the public.", sections: [{ heading: "You must not", bullets: ["Use services for fraud, deception, harassment or intimidation", "Impersonate another person or target an account without authority", "Promote illegal content, hate, violence or exploitation", "Manipulate political or civic processes", "Attempt to bypass service limits, security or payment controls", "Submit malware, stolen credentials or private information", "Resell or use services in a way that violates applicable law or platform rules"] }, { heading: "Enforcement", paragraphs: ["We may reject orders, restrict features, suspend accounts, preserve relevant records or cooperate with lawful investigations where misuse is suspected. Enforcement decisions consider severity, repetition and risk."] }] },
  "cookie-policy": { title: "Cookie Policy", lead: "How browser storage supports secure account access.", sections: [{ heading: "Essential storage", paragraphs: ["Social Booster uses essential session cookies to keep signed-in users authenticated and protect private account pages. These cookies are necessary for the service to function."] }, { heading: "Optional technologies", paragraphs: ["Optional analytics or advertising technologies should not be enabled without appropriate notice and consent controls. This policy will be updated if those technologies are introduced."] }, { heading: "Managing cookies", paragraphs: ["Your browser can delete or block cookies, but blocking essential cookies will prevent account login and dashboard access."] }] },
};

const general: Record<string, Page> = {
  api: { title: "API access", lead: "Programmatic access is being prepared for approved business customers.", sections: [{ heading: "Availability", paragraphs: ["Public API access is not currently offered. Documentation, authentication requirements and usage limits will be published before access is enabled."] }] },
};

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params, item = pages[slug] || general[slug]; return item ? { title: item.title, description: item.lead, alternates: { canonical: `/${slug}` } } : { title: "Page not found", robots: { index: false } }; }

export default async function Page({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params, item = pages[slug] || general[slug]; if (!item) notFound();
  const legal = ["terms", "privacy", "refund-policy", "acceptable-use", "cookie-policy"].includes(slug);
  return <><SiteHeader /><main className="shell" style={{ minHeight: "65vh", padding: "90px 0" }}><span className="eyebrow">Social Booster</span><h1 style={{ fontSize: "clamp(2.8rem,7vw,5.2rem)", letterSpacing: "-.06em", maxWidth: 900, margin: "18px 0" }}>{item.title}</h1><p className="muted" style={{ fontSize: 20, lineHeight: 1.7, maxWidth: 760 }}>{item.lead}</p>{legal ? <p className="muted">Effective date: {updated}</p> : null}<div className="legal-wrap" style={{ marginTop: 44 }}><article className="glass legal-copy">{item.sections.map((section) => <section key={section.heading}><h2>{section.heading}</h2>{section.paragraphs?.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}{section.bullets ? <ul>{section.bullets.map((bullet) => <li key={bullet}>{bullet}</li>)}</ul> : null}</section>)}</article><aside className="glass legal-nav"><strong>{legal ? "Policies" : "Explore"}</strong>{(legal ? [["Terms", "/terms"], ["Privacy", "/privacy"], ["Refunds", "/refund-policy"], ["Acceptable use", "/acceptable-use"], ["Cookies", "/cookie-policy"]] : [["How it works", "/how-it-works"], ["FAQ", "/faq"], ["Contact", "/contact"], ["Create account", "/register"]]).map(([label, href]) => <Link key={href} href={href}>{label}</Link>)}</aside></div></main><SiteFooter /></>;
}
