"use server";
import { FieldValue } from "firebase-admin/firestore";
import { revalidatePath } from "next/cache";
import { adminDb } from "@/lib/firebase/admin";
import { requireUser } from "@/lib/firebase/session";
import { FollowsPanelClient } from "@/lib/providers/followspanel";

async function ownedOrder(id: string, userId: string) { const ref = adminDb().collection("orders").doc(id), snapshot = await ref.get(); if (!snapshot.exists || snapshot.get("userId") !== userId) throw new Error("Order not found"); return { ref, data: snapshot.data()! }; }
export async function requestRefill(formData: FormData) { const user = await requireUser(), id = String(formData.get("id") || ""), { data } = await ownedOrder(id, user.uid); if (!data.refillSupported || !data.providerOrderId || data.status !== "completed") throw new Error("Refill is not available"); const db = adminDb(), refillRef = db.collection("refills").doc(id), existing = await refillRef.get(); if (existing.exists) return; await refillRef.create({ orderId: id, userId: user.uid, status: "submitting", createdAt: FieldValue.serverTimestamp() }); try { const result = await new FollowsPanelClient().refill(data.providerOrderId); await refillRef.set({ providerRefillId: result.refill, status: "pending", updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } catch { await refillRef.set({ status: "provider_confirmation_required", updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } revalidatePath(`/dashboard/orders/${id}`); revalidatePath("/dashboard/refills"); }
export async function requestCancellation(formData: FormData) { const user = await requireUser(), id = String(formData.get("id") || ""), { ref, data } = await ownedOrder(id, user.uid); if (!data.cancelSupported || !data.providerOrderId || !["pending", "processing", "in_progress"].includes(data.status)) throw new Error("Cancellation is not available"); if (data.cancellationRequestedAt) return; await ref.set({ cancellationRequestedAt: FieldValue.serverTimestamp(), status: "cancel_requested", updatedAt: FieldValue.serverTimestamp() }, { merge: true }); try { await new FollowsPanelClient().cancel([data.providerOrderId]); } catch { await ref.set({ cancellationStatus: "provider_confirmation_required", updatedAt: FieldValue.serverTimestamp() }, { merge: true }); } revalidatePath(`/dashboard/orders/${id}`); }
