import { AppShell } from "@/components/app-shell";
import { adminDb } from "@/lib/firebase/admin";
import { formatMoney } from "@/lib/money";
import { adjustWallet } from "./actions";

export const dynamic = "force-dynamic";
export default async function AdminWalletsPage() {
  const snapshot = await adminDb().collection("wallets").limit(100).get();
  return <AppShell admin><span className="eyebrow">Financial controls</span><h1 className="page-heading">Wallets</h1><div className="glass card" style={{ marginBottom: 22 }}><h2>Audited adjustment</h2><p className="muted">Use only for a documented correction. Every submission creates immutable transaction, ledger and audit records.</p><form action={adjustWallet} className="form-grid"><input className="field form-span" name="userId" placeholder="Firebase user UID" required /><input className="field" name="amount" inputMode="decimal" placeholder="Amount" required /><select className="field" name="direction"><option value="credit">Credit</option><option value="debit">Debit</option></select><select className="field" name="currency" defaultValue="NGN"><option>NGN</option><option>USD</option><option>GBP</option><option>EUR</option><option>CAD</option><option>AUD</option></select><input className="field" name="reason" placeholder="Required reason" minLength={5} required /><div className="form-span"><button className="btn primary">Post audited adjustment</button></div></form></div>{snapshot.empty ? <div className="glass card"><h2>No wallets yet</h2><p className="muted">A wallet is created automatically when a signed-in customer opens their wallet page.</p></div> : <div style={{ display: "grid", gap: 12 }}>{snapshot.docs.map((doc) => { const item = doc.data(), available = Number(item.availableMinor ?? item.balanceMinor ?? 0); return <article className="glass card" key={doc.id}><strong style={{ overflowWrap: "anywhere" }}>{doc.id}</strong><p className="muted">Available {formatMoney(BigInt(available), item.currency || "NGN")} · Reserved {formatMoney(BigInt(item.reservedMinor || 0), item.currency || "NGN")}</p></article>; })}</div>}</AppShell>;
}
