import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { guides, type GuideSlug } from "@/lib/content";
export function generateStaticParams() { return Object.keys(guides).map((slug) => ({ slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params, guide = guides[slug as GuideSlug]; return guide ? { title: guide.title, description: guide.description, alternates: { canonical: `/blog/${slug}` }, openGraph: { type: "article", title: guide.title, description: guide.description } } : { title: "Guide not found", robots: { index: false } }; }
export default async function Post({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params, guide = guides[slug as GuideSlug]; if (!guide) notFound(); return <><SiteHeader /><main className="shell" style={{ minHeight: "65vh", padding: "90px 0", maxWidth: 900 }}><Link href="/blog" className="muted">← All guides</Link><p className="eyebrow" style={{ marginTop: 36 }}>Social media marketing · Nigeria</p><h1 style={{ fontSize: "clamp(2.6rem,7vw,5rem)", letterSpacing: "-.055em" }}>{guide.title}</h1><p className="muted" style={{ fontSize: 20, lineHeight: 1.8 }}>{guide.description}</p>{guide.sections.map((section) => <section key={section.heading} style={{ marginTop: 42 }}><h2 style={{ fontSize: 30 }}>{section.heading}</h2><p className="muted" style={{ fontSize: 18, lineHeight: 1.9 }}>{section.body}</p></section>)}<div className="glass card" style={{ marginTop: 50 }}><h2>Explore transparent NGN pricing</h2><p className="muted">Browse reviewed social media marketing services and check the current naira price before ordering.</p><Link className="btn primary" href="/services">View services</Link></div></main><SiteFooter /></>; }
