import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { adminDb } from "@/lib/firebase/admin";
import { isFirestoreQuotaError } from "@/lib/firebase/errors";
import { serviceSellingRateNgnMinor } from "@/lib/currency";
import { formatMoney } from "@/lib/money";

export const metadata: Metadata = { title: "Social Media Marketing Services in Nigeria", description: "Browse the complete synchronized FollowsPanel service catalog with transparent Nigerian naira pricing plus a fixed 40% markup.", alternates: { canonical: "/services" } };
export const dynamic = "force-dynamic";
type CatalogService = { id: string; name: string; categoryName: string; minQuantity: number; maxQuantity: number; refillSupported: boolean; cancelSupported: boolean; sellingRateMinor: number };

export default async function Services({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  const { q = "" } = await searchParams, normalized = q.trim().toLowerCase();
  let services: CatalogService[] = [], quotaExhausted = false;
  try { const snapshot = await adminDb().collection("services").where("active", "==", true).get(); services = snapshot.docs.map((doc) => { const data = doc.data(); return { id: doc.id, ...data, sellingRateMinor: Number(serviceSellingRateNgnMinor(data)) } as CatalogService; }).filter((item) => !normalized || item.name.toLowerCase().includes(normalized) || item.categoryName.toLowerCase().includes(normalized)).sort((a, b) => a.categoryName.localeCompare(b.categoryName) || a.name.localeCompare(b.name)); } catch (error) { if (!isFirestoreQuotaError(error)) throw error; quotaExhausted = true; }
  return <><SiteHeader /><main className="shell" style={{ minHeight: "65vh", padding: "80px 0" }}><span className="eyebrow">Complete synchronized catalog</span><h1 style={{ fontSize: "clamp(2.8rem,7vw,5rem)", letterSpacing: "-.055em", margin: "14px 0" }}>Every FollowsPanel service, professionally organized.</h1><p className="muted" style={{ fontSize: 18, maxWidth: 780, lineHeight: 1.7 }}>All active API services are synchronized in Nigerian naira. Each customer price is the exact FollowsPanel NGN rate plus 40%.</p><form className="glass" style={{ display: "flex", gap: 10, maxWidth: 820, margin: "32px 0", padding: 10, borderRadius: 16 }}><input className="field" name="q" defaultValue={q} aria-label="Search all services" placeholder="Search category, platform or service…" /><button className="btn primary">Search</button></form>{!quotaExhausted && <p className="muted">{services.length.toLocaleString("en-NG")} service{services.length === 1 ? "" : "s"} found</p>}{quotaExhausted ? <div className="glass card"><h2>Catalog temporarily unavailable</h2><p className="muted">Please check again shortly.</p></div> : services.length === 0 ? <div className="glass card"><h2>No services found</h2><p className="muted">Try a different platform, category or service name.</p></div> : <div style={{ display: "grid", gap: 14 }}>{services.map((service) => <article className="glass card" key={service.id}><div style={{ display: "flex", justifyContent: "space-between", gap: 18, flexWrap: "wrap", alignItems: "center" }}><div style={{ maxWidth: 820 }}><p className="eyebrow" style={{ margin: 0 }}>{service.categoryName}</p><h2 style={{ fontSize: 19, margin: "9px 0" }}>{service.name}</h2><p className="muted" style={{ margin: 0 }}>ID {service.id} · Min {service.minQuantity.toLocaleString("en-NG")} · Max {service.maxQuantity.toLocaleString("en-NG")} · Refill {service.refillSupported ? "Available" : "No"} · Cancel {service.cancelSupported ? "Available" : "No"}</p></div><div style={{ textAlign: "right", minWidth: 190 }}><strong style={{ fontSize: 25 }}>{formatMoney(BigInt(service.sellingRateMinor), "NGN")}</strong><p className="muted" style={{ margin: "5px 0 12px" }}>per 1,000</p><Link className="btn" href={`/services/${service.id}`}>View service</Link></div></div></article>)}</div>}</main><SiteFooter /></>;
}
