create extension if not exists pgcrypto;
create type public.order_status as enum ('pending','processing','in_progress','completed','partial','cancelled','failed');
create type public.ledger_type as enum ('deposit','order_debit','refund','admin_adjustment','promotional_credit');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,display_name text,currency char(3) not null default 'USD',suspended_at timestamptz,created_at timestamptz not null default now());
create table public.roles(user_id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in('customer','support','admin')),granted_by uuid references auth.users(id),created_at timestamptz not null default now());
create table public.wallets(user_id uuid primary key references auth.users(id) on delete cascade,currency char(3) not null default 'USD',balance_minor bigint not null default 0 check(balance_minor>=0),version bigint not null default 0,updated_at timestamptz not null default now());
create table public.wallet_transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),type public.ledger_type not null,amount_minor bigint not null,currency char(3) not null,idempotency_key text not null unique,reference text,status text not null default 'posted',created_at timestamptz not null default now());
create table public.wallet_ledger(id bigint generated always as identity primary key,wallet_user_id uuid not null references public.wallets(user_id),transaction_id uuid not null references public.wallet_transactions(id),delta_minor bigint not null,balance_after_minor bigint not null check(balance_after_minor>=0),created_at timestamptz not null default now(),unique(wallet_user_id,transaction_id));
create table public.service_categories(id uuid primary key default gen_random_uuid(),name text not null unique,slug text not null unique,active boolean not null default true,sort_order int not null default 0);
create table public.provider_services(id uuid primary key default gen_random_uuid(),provider_service_id bigint not null unique,category_name text not null,name text not null,type text not null,rate_text text not null,min_quantity int not null,max_quantity int not null,refill_supported boolean not null,cancel_supported boolean not null,is_active boolean not null default true,last_synced_at timestamptz not null,provider_currency char(3) not null default 'USD');
create table public.services(id uuid primary key default gen_random_uuid(),provider_service_id uuid not null references public.provider_services(id),category_id uuid references public.service_categories(id),slug text unique,active boolean not null default true,margin_bps int not null default 4000 check(margin_bps between 0 and 9999),override_rate_minor bigint,created_at timestamptz not null default now());
create table public.orders(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),service_id uuid not null references public.services(id),provider_order_id bigint,target text not null,quantity int not null check(quantity>0),status public.order_status not null default 'pending',idempotency_key text not null unique,provider_cost_minor bigint not null,customer_price_minor bigint not null,gross_profit_minor bigint not null,currency char(3) not null,exchange_rate numeric(20,8) not null,provider_status text,provider_charge_minor bigint,start_count bigint,remains bigint,last_provider_update timestamptz,created_at timestamptz not null default now());
create index orders_user_created_idx on public.orders(user_id,created_at desc);create index orders_sync_idx on public.orders(status,last_provider_update) where status not in('completed','cancelled','failed');
create table public.order_events(id bigint generated always as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,status public.order_status not null,detail jsonb not null default '{}',created_at timestamptz not null default now());
create table public.refills(id uuid primary key default gen_random_uuid(),order_id uuid not null references public.orders(id),user_id uuid not null references auth.users(id),provider_refill_id bigint,status text not null default 'pending',created_at timestamptz not null default now());
create table public.transactions(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),provider text,external_id text,amount_minor bigint not null,currency char(3) not null,status text not null,idempotency_key text not null unique,created_at timestamptz not null default now());
create table public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),subject text not null,department text not null,priority text not null,status text not null default 'open',created_at timestamptz not null default now());
create table public.support_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete cascade,sender_id uuid not null references auth.users(id),body text not null,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),type text not null,title text not null,body text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.customer_api_keys(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id),prefix text not null,key_hash text not null unique,scopes text[] not null default '{}',last_used_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now());
create table public.provider_sync_runs(id uuid primary key default gen_random_uuid(),kind text not null,status text not null,records_count int not null default 0,error text,started_at timestamptz not null default now(),finished_at timestamptz);
create table public.payment_events(id uuid primary key default gen_random_uuid(),provider text not null,event_id text not null,payload jsonb not null,status text not null,created_at timestamptz not null default now(),unique(provider,event_id));
create table public.audit_logs(id bigint generated always as identity primary key,actor_id uuid references auth.users(id),action text not null,entity_type text not null,entity_id text,metadata jsonb not null default '{}',ip_hash text,created_at timestamptz not null default now());
create table public.blog_posts(id uuid primary key default gen_random_uuid(),slug text not null unique,title text not null,description text not null,body text not null,status text not null default 'draft',published_at timestamptz,author_id uuid references auth.users(id),created_at timestamptz not null default now());
create table public.admin_settings(key text primary key,value jsonb not null,updated_by uuid references auth.users(id),updated_at timestamptz not null default now());
create table public.exchange_rates(base char(3) not null,quote char(3) not null,rate numeric(20,8) not null check(rate>0),source text not null,fetched_at timestamptz not null,primary key(base,quote));

alter table public.profiles enable row level security;alter table public.roles enable row level security;alter table public.wallets enable row level security;alter table public.wallet_transactions enable row level security;alter table public.wallet_ledger enable row level security;alter table public.orders enable row level security;alter table public.order_events enable row level security;alter table public.refills enable row level security;alter table public.transactions enable row level security;alter table public.support_tickets enable row level security;alter table public.support_messages enable row level security;alter table public.notifications enable row level security;alter table public.customer_api_keys enable row level security;
create policy profiles_own_select on public.profiles for select to authenticated using((select auth.uid())=id);create policy profiles_own_update on public.profiles for update to authenticated using((select auth.uid())=id) with check((select auth.uid())=id);
create policy wallets_own_select on public.wallets for select to authenticated using((select auth.uid())=user_id);create policy wallet_transactions_own_select on public.wallet_transactions for select to authenticated using((select auth.uid())=user_id);create policy wallet_ledger_own_select on public.wallet_ledger for select to authenticated using((select auth.uid())=wallet_user_id);
create policy orders_own_select on public.orders for select to authenticated using((select auth.uid())=user_id);create policy events_own_select on public.order_events for select to authenticated using(exists(select 1 from public.orders o where o.id=order_id and o.user_id=(select auth.uid())));create policy refills_own_select on public.refills for select to authenticated using((select auth.uid())=user_id);create policy transactions_own_select on public.transactions for select to authenticated using((select auth.uid())=user_id);create policy tickets_own_select on public.support_tickets for select to authenticated using((select auth.uid())=user_id);create policy tickets_own_insert on public.support_tickets for insert to authenticated with check((select auth.uid())=user_id);create policy messages_own_select on public.support_messages for select to authenticated using(exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=(select auth.uid())));create policy notifications_own_select on public.notifications for select to authenticated using((select auth.uid())=user_id);create policy api_keys_own_select on public.customer_api_keys for select to authenticated using((select auth.uid())=user_id);
revoke all on public.roles from anon,authenticated;revoke insert,update,delete on public.wallets,public.wallet_ledger,public.wallet_transactions,public.orders,public.order_events,public.transactions,public.payment_events from anon,authenticated;

create schema if not exists private;revoke all on schema private from public;
create or replace function private.post_wallet(p_user uuid,p_type public.ledger_type,p_amount bigint,p_currency char(3),p_key text,p_reference text default null) returns uuid language plpgsql security definer set search_path='' as $$declare v_tx uuid;v_balance bigint;begin if p_amount=0 then raise exception 'zero amount';end if;select id into v_tx from public.wallet_transactions where idempotency_key=p_key;if found then return v_tx;end if;select balance_minor into v_balance from public.wallets where user_id=p_user for update;if not found then raise exception 'wallet missing';end if;v_balance:=v_balance+p_amount;if v_balance<0 then raise exception 'insufficient funds';end if;insert into public.wallet_transactions(user_id,type,amount_minor,currency,idempotency_key,reference)values(p_user,p_type,p_amount,p_currency,p_key,p_reference)returning id into v_tx;update public.wallets set balance_minor=v_balance,version=version+1,updated_at=now()where user_id=p_user;insert into public.wallet_ledger(wallet_user_id,transaction_id,delta_minor,balance_after_minor)values(p_user,v_tx,p_amount,v_balance);return v_tx;end$$;revoke all on function private.post_wallet(uuid,public.ledger_type,bigint,char,text,text) from public;
